name: Compilar TFS Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Clonar Codigo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Instalar vcpkg Padrao
      run: |
        cd C:\
        git clone https://github.com
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install

    - name: Instalar Dependencias
      run: |
        C:\vcpkg\vcpkg.exe install --triplet x64-windows boost-iostreams boost-asio boost-system boost-variant boost-lockfree boost-locale boost-beast boost-json luajit libmariadb pugixml openssl fmt zlib

    - name: Compilar EXE (Ignorando Avisos)
      run: |
        msbuild vc17/theforgottenserver.vcxproj /p:Configuration=Release /p:Platform=x64 /p:TreatWarningsAsErrors=false

    - name: Salvar Executavel
      uses: actions/upload-artifact@v4
      with:
        name: TFS-860-Pronto
        path: vc17/x64/Release/theforgottenserver.exe
